name: Build oidc
run-name: Build image with tag ${{ inputs.image_tag }}

on:
  workflow_call:
    inputs:
      image_tag:
        required: true
        type: string
      environment:
        required: true
        type: string
      name_app:
        required: true
        type: string
      project:
        required: true
        type: string
      dockerfile:
        required: true
        type: string
    secrets:
      GH_TOKEN:
        required: true
      PAT_TOKEN:
        required: false
      AWS_CI_ROLE:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    permissions:
      id-token: write
      contents: read
      packages: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: tag ${{ inputs.image_tag }}
      run: echo ${{ inputs.image_tag }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        audience: sts.amazonaws.com
        role-to-assume: ${{ secrets.AWS_CI_ROLE }}
        aws-region: ${{ vars.AWS_REGION }}

    - name: Login to ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Debug ECR Registry
      run: |
        ls -la
        echo "${{ github.event.inputs.catalog }}"
        echo "ECR Registry: ${{ steps.login-ecr.outputs.registry }}/${{ vars.ECR_CATALOG_NAME }}:${{ inputs.image_tag }}"

    - name: Create .npmrc
      run: |
        echo "@acme-corp:registry=https://npm.pkg.github.com/" > .npmrc
        echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc

      # env:
      #   node-auth-token: ${{ secrets.PAT_TOKEN }}

    - name: Build and push Docker image
      run: |

        ECR_CATALOG="${{ inputs.project }}-${{ inputs.name_app }}"
        docker build --secret id=npmrc,src=.npmrc --build-arg BUILD_TIMESTAMP=$(date +%Y%m%d%H%M%S) -t ${{ steps.login-ecr.outputs.registry }}/$ECR_CATALOG:${{ inputs.image_tag }} . -f ${{ inputs.dockerfile }}
        docker push ${{ steps.login-ecr.outputs.registry }}/$ECR_CATALOG:${{ inputs.image_tag }}

    - name: Save tag to Parameter Store
      run: |
        aws ssm put-parameter \
          --name "/oidc/${{ inputs.environment }}/image-tag" \
          --value "${{ inputs.image_tag }}" \
          --type "String" \
          --overwrite