services:
  postgres-zabbix:
    image: postgres:15.4
    container_name: postgres-zabbix
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
      POSTGRES_USER: dbuser

  zabbix:
    image: zabbix/zabbix-server-pgsql:7.2.10-ubuntu
    container_name: zabbix
    environment:
      DB_SERVER_HOST: postgres-zabbix
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
      ZBX_CACHESIZE: 128M
    ports:
      - 10051:10051
    depends_on:
      - postgres-zabbix


  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:7.2.10-ubuntu
    container_name: zabbix-web
    environment:
      DB_SERVER_HOST: postgres-zabbix
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
      ZBX_SERVER_HOST: zabbix
      PHP_TZ: Europe/Moscow
    ports:
      - '127.0.0.1:8010:8080'
    depends_on:
      - zabbix

  grafana:
    image: grafana/grafana-oss:latest
    volumes:
      - ./data:/var/lib/grafana
      - ./grafana-dh/provisioning/:/etc/grafana/provisioning/
      - ./log:/var/log/grafana
    environment:
      - GF_PLUGINS_PREINSTALL=alexanderzobnin-zabbix-app
    ports:
      - '127.0.0.1:3000:3000'

  loki:
    image: grafana/loki:2.8.0
    ports:
      - "127.0.0.1:3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config:/etc/loki
      - ./loki:/loki
