apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-service
  namespace: {{ .Values.namespace }}
  labels:
    env: {{ .Values.env_label }}
spec:
  selector:
    project: {{ .Values.name }}
  ports:
    - name: {{ .Values.name }}-listener
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
