namespace: app
env_label: dev

image:
  repository: cr.yandex/crpm0vvs5g97ip7a7ged/app
  tag: latest
  pullPolicy: Always

resources:
  requests:
    memory: 200Mi
    cpu: 100m
  limits:
    memory: 300Mi
    cpu: 100m

hpa:
  minReplicas: 1
  maxReplicas: 2
  cpuUtilization: 90
  memoryUtilization: 90
