{{- range .Values.environments }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}-secret
  labels:
    app: {{ .name }}
    env: {{ .name }}
type: Opaque
stringData:
  {{- range $key, $value := .secrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
