import psycopg2
from psycopg2 import sql

db_host = 'localhost'
db_name = 'vmware'
db_user = 'postgres'
db_password = ''
db_port = '5432'
table_name = 'ip_addresses'

filtered_ips = ['127.0.0.1','203.0.113.30']

# Insert IP addresses into the PostgreSQL table
conn = psycopg2.connect(host=db_host, dbname=db_name, user=db_user, password=db_password, port=db_port)
cur = conn.cursor()

print(filtered_ips)
cur.execute(sql.SQL("CREATE TABLE IF NOT EXISTS {} (id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, ip TEXT, CONSTRAINT ip UNIQUE (ip))").format(sql.Identifier(table_name)))

# Remove records not present in filtered_ips
filtered_ips_tuple = tuple(filtered_ips)  # Convert the list to a tuple
delete_query = sql.SQL("DELETE FROM {} WHERE ip NOT IN ({})").format(
    sql.Identifier(table_name),
    sql.SQL(',').join(sql.Placeholder() * len(filtered_ips_tuple))
)
cur.execute(delete_query, filtered_ips_tuple)

for ip in filtered_ips:
    cur.execute(sql.SQL("INSERT INTO {} (ip) VALUES (%s) ON CONFLICT (ip) DO NOTHING").format(sql.Identifier(table_name)), [ip])

conn.commit()
cur.close()
conn.close()

# Print the list of IP addresses
for ip in filtered_ips:
    print(ip)
